### ISSUE TITLE
Change data source?

### ISSUE THREAD

**Issue by CloCkWeRX** [planningalerts-scrapers/ballarat#1]
Was https://github.com/openaustralia/planningalerts/issues/672

It looks like the Ballarat DA data is now being uploaded daily to data.gov.au. See https://twitter.com/mattswards/status/605591831523393536

On data.gov.au at https://data.gov.au/dataset/ballarat-planning-applications-currently-on-advertising/resource/2db587db-4552-482a-aa69-913e0ee9cf03

We already have a scraper for Ballarat but structured data is much nicer ;-)

**Comment by henare** [comment]
What a joke. As usual for the rare circumstances when data on data.gov.au seems even remotely useful this turns out to look good at first pass but is useless. This JSON [doesn't even have a single application from this year](https://data.gov.au/dataset/f80007d1-fe53-4fa7-b021-991f0edd4a5c/resource/d83ed724-4dc9-48d8-af70-81f9c0dc341b/download/ballaratcurrentplanningapps.json). What's the point? How frustrating.
